language: c
compiler:
  - gcc

addons:
    apt:
      packages:
         - bc
         - lftp
         - gcc-multilib
         - u-boot-tools
         - lzop
         - libelf-dev
         - gcc-4.6-plugin-dev
         - ccache


cache:
  apt: true
#  ccache: true
  directories:
     - $HOME/local
#    - $HOME/.ccache

git:
  depth: 1

#sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
#   - secure: "qoWQ6Bi/n4mVP+wlDINo3cPQDfC8V7Yofjh+WmBxKwLqP+RPzCgEkbPqitAZhRpr2QLe/Eehfwx0WvuEJjucOm5lWEkFpY32VCXCjswK5R4S1G2LPobo9BOLkPY9pjahru56HPWDGAbIVQ74UXmnkPCFfOOOZLLXry1pzbKfDNdX+LryTvtrK9e4MlvBIp2xNQgzZRLWos8JoxncvW04jYaRBAQ9zn+DWiZxlEHzdClPLEQsJnKGmk3LaWCV1CRg0ZXQvecieEWmdN5mrpNF4H8ry9A4No3rSXMgloucJEWaHqCMFYXuWcqgQY4GHemHiF06bM6LF4fFAPWupFW++e03NRFrbm7KF3xWpSReTltrKA0kz2ctdWvfFN+DZSZ+5R2rmcoFG3dp+7mO5WcT5gTfHrF8ZxfHMFR9MqQHMiOntpuXXZTMq7uaqURRlzFeZ0rFluzK7S2EEbn1nQEuWdoGvMBSRFHFU5nvXEq1ooQRAY/K15XXHTHni9/9yU/+9+hG2tDbv3gtkYMnHFjtuDrQeQkfTKuWe94B+lVmWaC7ozO4agE555bQXYGLP2KF9DmqP1dkRLSGNAMJXN6NqA3l9ufk16mo+fjxT7YnN4mo5/xxMpxlN+e3OLHzrpZuwS/bvxK2kEGJdDvAprNWwkfy7VA+8dvkkPjeFS07tyk="


#  coverity_scan:
#    project:
#      name: "sudipm-mukherjee/parport"
#      description: "linux 4.2"
#    notification_email: sudipm.mukherjee@gmail.com
#    build_command_prepend: "make allmodconfig; make oldconfig && make prepare;"
#    build_command:   "make -j2"
#    branch_pattern: linux
  matrix:
      - fld="i386,defconfig"
      - fld="x86_64,defconfig"
      - fld="alpha,defconfig"
      - fld="arm,defconfig"
      - fld="blackfin,defconfig"
      - fld="cris,defconfig"
      - fld="m32r,defconfig"
      - fld="frv,defconfig"
      - fld="m68k,defconfig"
      - fld="mips,defconfig"
      - fld="s390,defconfig"
      - fld="sparc,defconfig"
      - fld="sparc64,defconfig"
      - fld="tilegx,defconfig"
      - fld="tilepro,defconfig"
      - fld="xtensa,defconfig"
      - fld="nios2,defconfig"
      - fld="i386,allmodconfig"
      - fld="x86_64,allmodconfig"
      - fld="alpha,allmodconfig"
      - fld="arm,allmodconfig"
      - fld="m32r,allmodconfig"
      - fld="frv,allmodconfig"
      - fld="m32r,allyesconfig"
      - fld="m68k,allmodconfig"
      - fld="mips,allmodconfig"
      - fld="s390,allmodconfig"
      - fld="sparc,allmodconfig"
      - fld="sparc64,allmodconfig"
      - fld="tilegx,allmodconfig"
      - fld="tilepro,allmodconfig"
      - fld="xtensa,allmodconfig"
      - fld="nios2,allmodconfig"
      - fld="m32r,m32104ut_defconfig"
      - fld="m32r,m32700ut.up_defconfig"
      - fld="m32r,mappi.nommu_defconfig"
      - fld="m32r,mappi.smp_defconfig"
      - fld="m32r,mappi.up_defconfig"
      - fld="m32r,mappi2.opsp_defconfig"
      - fld="m32r,mappi2.vdec2_defconfig"
      - fld="m32r,mappi3.smp_defconfig"
      - fld="m32r,oaks32r_defconfig"
      - fld="m32r,opsput_defconfig"
      - fld="m32r,usrv_defconfig"
      - fld="mips,ar7_defconfig"
      - fld="mips,ath79_defconfig"
      - fld="mips,bcm47xx_defconfig"
      - fld="mips,bcm63xx_defconfig"
      - fld="mips,bigsur_defconfig"
      - fld="mips,bmips_be_defconfig"
      - fld="mips,bmips_stb_defconfig"
      - fld="mips,capcella_defconfig"
      - fld="mips,cavium_octeon_defconfig"
      - fld="mips,ci20_defconfig"
      - fld="mips,cobalt_defconfig"
      - fld="mips,db1xxx_defconfig"
      - fld="mips,decstation_defconfig"
      - fld="mips,e55_defconfig"
      - fld="mips,fuloong2e_defconfig"
      - fld="mips,gpr_defconfig"
      - fld="mips,ip27_defconfig"
      - fld="mips,ip32_defconfig"
      - fld="mips,jazz_defconfig"
      - fld="mips,jmr3927_defconfig"
      - fld="mips,lasat_defconfig"
      - fld="mips,lemote2f_defconfig"
      - fld="mips,loongson1b_defconfig"
      - fld="mips,malta_defconfig"
      - fld="mips,malta_kvm_defconfig"
      - fld="mips,malta_kvm_guest_defconfig"
      - fld="mips,maltaaprp_defconfig"
      - fld="mips,maltasmvp_defconfig"
      - fld="mips,maltasmvp_eva_defconfig"
      - fld="mips,maltaup_defconfig"
      - fld="mips,maltaup_xpa_defconfig"
      - fld="mips,markeins_defconfig"
      - fld="mips,mips_paravirt_defconfig"
      - fld="mips,mpc30x_defconfig"
      - fld="mips,msp71xx_defconfig"
      - fld="mips,mtx1_defconfig"
      - fld="mips,nlm_xlp_defconfig"
      - fld="mips,nlm_xlr_defconfig"
      - fld="mips,pic32mzda_defconfig"
      - fld="mips,pistachio_defconfig"
      - fld="mips,pnx8335_stb225_defconfig"
      - fld="mips,qi_lb60_defconfig"
      - fld="mips,rb532_defconfig"
      - fld="mips,rbtx49xx_defconfig"
      - fld="mips,rm200_defconfig"
      - fld="mips,rt305x_defconfig"
      - fld="mips,sb1250_swarm_defconfig"
      - fld="mips,tb0219_defconfig"
      - fld="mips,tb0226_defconfig"
      - fld="mips,tb0287_defconfig"
      - fld="mips,workpad_defconfig"
      - fld="mips,xilfpga_defconfig"
      - fld="mips,xway_defconfig"

before_script:
     - mkdir -p $HOME/bin
     - cp ./make.cross $HOME/bin/.

script:
    - a=(`echo $fld | tr ',' '\n'`)
    - mkdir obj-${a[0]}
    - make.cross ARCH=${a[0]} ${a[1]}
    - if [ "$fld" == "m32r,allmodconfig" ]; then sed -i 's/CONFIG_CPU_LITTLE_ENDIAN/CONFIG_CPU_BIG_ENDIAN/g' obj-m32r/.config; fi
    - make.cross ARCH=${a[0]} olddefconfig
    - make.cross ARCH=${a[0]} prepare
    - make.cross ARCH=${a[0]} 2> ${a[0]}_err
    - echo $?
    - cat ${a[0]}_err
# sed -i 's/CONFIG_CPU_LITTLE_ENDIAN/CONFIG_CPU_BIG_ENDIAN/g' obj-m32r/.config
# make.cross ARCH=m32r olddefconfig

after_script:
    - b=`git log -1 | grep next`
    - mkdir push_git
    - cd push_git
#    - git init
#    - git remote add gitw https://github.com/sudipm-mukherjee/next-warnings.git
#    - git fetch gitw
#    - git reset --hard gitw/${a[0]}_${a[1]}
#    - cp ../${a[0]}_err ${a[0]}_${a[1]}_err
#    - git add ${a[0]}_${a[1]}_err
#    - git -c user.name='sudip' -c user.email='sudipm.mukherjee@gmail.com' commit -m $b
#    - git push -f -q https://sudipm-mukherjee:$GITHUB_API_KEY@github.com/sudipm-mukherjee/next-warnings.git master:${a[0]}_${a[1]}

notifications:
    email:
      recipients:
            - sudipm.mukherjee@gmail.com
      on_success: always
      on_failure: always
