language: c
compiler:
  - gcc

addons:
    apt:
      packages:
         - bc
         - lftp
         - gcc-multilib
         - uboot-mkimage	 

cache:
  apt: true
#  ccache: true
  directories:
     - $HOME/local
#     - $HOME/.ccache

#sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
#   - secure: "qoWQ6Bi/n4mVP+wlDINo3cPQDfC8V7Yofjh+WmBxKwLqP+RPzCgEkbPqitAZhRpr2QLe/Eehfwx0WvuEJjucOm5lWEkFpY32VCXCjswK5R4S1G2LPobo9BOLkPY9pjahru56HPWDGAbIVQ74UXmnkPCFfOOOZLLXry1pzbKfDNdX+LryTvtrK9e4MlvBIp2xNQgzZRLWos8JoxncvW04jYaRBAQ9zn+DWiZxlEHzdClPLEQsJnKGmk3LaWCV1CRg0ZXQvecieEWmdN5mrpNF4H8ry9A4No3rSXMgloucJEWaHqCMFYXuWcqgQY4GHemHiF06bM6LF4fFAPWupFW++e03NRFrbm7KF3xWpSReTltrKA0kz2ctdWvfFN+DZSZ+5R2rmcoFG3dp+7mO5WcT5gTfHrF8ZxfHMFR9MqQHMiOntpuXXZTMq7uaqURRlzFeZ0rFluzK7S2EEbn1nQEuWdoGvMBSRFHFU5nvXEq1ooQRAY/K15XXHTHni9/9yU/+9+hG2tDbv3gtkYMnHFjtuDrQeQkfTKuWe94B+lVmWaC7ozO4agE555bQXYGLP2KF9DmqP1dkRLSGNAMJXN6NqA3l9ufk16mo+fjxT7YnN4mo5/xxMpxlN+e3OLHzrpZuwS/bvxK2kEGJdDvAprNWwkfy7VA+8dvkkPjeFS07tyk="


#  coverity_scan:
#    project:
#      name: "sudipm-mukherjee/parport"
#      description: "linux 4.2"
#    notification_email: sudipm.mukherjee@gmail.com
#    build_command_prepend: "make allmodconfig; make oldconfig && make prepare;"
#    build_command:   "make -j2"
#    branch_pattern: linux
  matrix:
      - fld="i386,defconfig"
      - fld="x86_64,defconfig"
      - fld="alpha,defconfig"
      - fld="arm,defconfig"
      - fld="avr32,defconfig"
      - fld="blackfin,defconfig"
      - fld="cris,defconfig"
      - fld="m32r,defconfig"
      - fld="m68k,defconfig"
      - fld="mips,defconfig"
      - fld="powerpc,defconfig"
      - fld="s390,defconfig"
      - fld="sparc,defconfig"
      - fld="sparc64,defconfig"
      - fld="tile,defconfig"
      - fld="tilegx,defconfig"
      - fld="xtensa,defconfig"
      - fld="i386,allnoconfig"
      - fld="x86_64,allnoconfig"
      - fld="alpha,allnoconfig"
      - fld="arm,allnoconfig"
      - fld="avr32,allnoconfig"
      - fld="blackfin,allnoconfig"
      - fld="cris,allnoconfig"
      - fld="m32r,allnoconfig"
      - fld="m68k,allnoconfig"
      - fld="mips,allnoconfig"
      - fld="powerpc,allnoconfig"
      - fld="s390,allnoconfig"
      - fld="sparc,allnoconfig"
      - fld="sparc64,allnoconfig"
      - fld="tile,allnoconfig"
      - fld="tilegx,allnoconfig"
      - fld="xtensa,allnoconfig"      
      - fld="i386,allmodconfig"
      - fld="x86_64,allmodconfig"
      - fld="alpha,allmodconfig"
      - fld="arm,allmodconfig"
      - fld="avr32,allmodconfig"
      - fld="blackfin,allmodconfig"
      - fld="cris,allmodconfig"
#      - fld=ia64
      - fld="m32r,allmodconfig"
      - fld="m68k,allmodconfig"
#      - fld=microblaze
      - fld="mips,allmodconfig"
#      - fld=mn10300
#      - fld=openrisc tough for now
#      - fld=parisc
      - fld="powerpc,allmodconfig"
      - fld="s390,allmodconfig"
#      - fld=sh
      - fld="sparc,allmodconfig"
      - fld="sparc64,allmodconfig"
      - fld="tile,allmodconfig"
      - fld="tilegx,allmodconfig"
#      - fld=um check contact geert
      - fld="xtensa,allmodconfig"
      - fld="i386,allyesconfig"
      - fld="x86_64,allyesconfig"
      - fld="alpha,allyesconfig"
      - fld="arm,allyesconfig"
      - fld="avr32,allyesconfig"
      - fld="blackfin,allyesconfig"
      - fld="cris,allyesconfig"
      - fld="m32r,allyesconfig"
      - fld="m68k,allyesconfig"
      - fld="mips,allyesconfig"
      - fld="powerpc,allyesconfig"
      - fld="s390,allyesconfig"
      - fld="sparc,allyesconfig"
      - fld="sparc64,allyesconfig"
      - fld="tile,allyesconfig"
      - fld="tilegx,allyesconfig"
      - fld="xtensa,allyesconfig"      

before_script:
     - mkdir -p $HOME/bin
     - cp ./make.cross $HOME/bin/.

script:
    - a=(`echo $fld | tr ',' '\n'`)
    - make.cross ARCH=${a[0]} ${a[1]}
    - make.cross ARCH=${a[0]} oldconfig
    - make.cross ARCH=${a[0]} prepare
    - make.cross ARCH=${a[0]}

notifications:
    email:
      recipients:
            - sudipm.mukherjee@gmail.com
      on_success: always
      on_failure: always
